server:
  port: 9191
  
  
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: 3is
    url: jdbc:sqlserver://localhost:1435;databaseName=IES
    username: sa
  jpa:
    hibernate:
      ddl-auto: 'update '
    properties:
      hibernate:
        format_sql: true
        show_sql: ' true '
  mvc:
    view:
      prefix: /views/
      suffix: .jsp